name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies (root workspaces)
        run: npm ci

      - name: Build client
        run: npm -w client run build

      - name: Run client unit tests
        run: npm -w client run test

      - name: Run API tests (start server + newman)
        run: npm run api:test

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run UI tests (Selenium)
        env:
          USE_IN_MEMORY_DB: 'true'
        run: npm test
